---
title: "Project 2: Linear Models"
author: "Samantha Earl, George Cadel-Munoz, Junyu Chen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Project 2: Linear Models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Project 2 for CS 499 (Machine Learning). Demonstrate both linear models with early stopping regularization and linear models with L2 regularization.


Binary Classification: LMLogisticLossL2CV, LMLogisticLossEarlyStoppingCV
```{r}
data(spam, package="ElemStatLearn")
#data(SAHeart, package="ElemStatLearn")
data(zip.train, package="ElemStatLearn")
is.01 <- zip.train[,1] %in% c(0,1)
data.list <- list(
  spam = list(
    features=as.matrix(spam[4601, 57]),
    labels = ifelse(spam$spam == "spam", 1, 0)),
  #SAheart = list(
  #  features=as.matrix(SAheart[462,9]),
  #  labels = ifelse(SAheart$SAheart == "SAheart", 1, 0)),
  zip.train = list(
    features = zip.train[is.01:7291, 256],
    labels=as.integer(zip.train[is.01, 1]))
)
n.folds <- 4
results.list <- list()
mean.loss.list <- list()

```